spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://main-project.csjzjz2589lr.ap-northeast-2.rds.amazonaws.com:3306/mainproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 30000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 25
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  tomcat:
    threads:
      max: 200
      min-spare: 20
    accept-count: 190
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
    encoding:
      force-response: true
mail:
  address:
    admin: admin@mail.com
jwt:
  secret:
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 240