spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://main-project.csjzjz2589lr.ap-northeast-2.rds.amazonaws.com:3306/mainproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
    encoding:
      force-response: true
mail:
  address:
    admin: admin@mail.com
jwt:
  secret:
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 360